### ISSUE TITLE
Single value not updated

### ISSUE THREAD

**Issue by romaindebay** [JustMaier/angular-ranger#10]
Hi, 

When you use "Single value", the value is not updated (position of bar is unchanged) when value change. (Missing watcher?)

Temp fix.: Add max-value like this:
`<angular-ranger min="1" max="100" step="1" value="s.v" max-value="s.v">`

Regards,

**Comment by JustMaier** [comment]
Hey @romaindebay it looks like your html might be a little off. It should be something more like:

```html
<angular-ranger min="1" max="100" step="1" value="s.v"></angular-ranger>
```

You just need to remove the `max-value` property as it's not needed for the single value ranger. Here's a little [demo](http://codepen.io/anon/pen/zNdMGW)

**Comment by romaindebay** [comment]
Hey @JustMaier, I think you haven't understand the issue.
Please check this [demo ](http://codepen.io/anon/pen/vgeGpa)and try to increment the value, you'll see the position of bar will not changed. Setting the "max-value" in html directive is a temp. solution.

**Comment by JustMaier** [comment]
Hey @romaindebay, I've just fixed the bug. Please grab the latest version :)
