### ISSUE TITLE
Update Bower package

### ISSUE THREAD

**Issue by PierrickGT** [JustMaier/angular-ranger#2]
Hi,

If you want 'bower install' to work with the last update and allow other github users to install your package with bower, you need to register your package again.
Here is what you have to do: http://bower.io/docs/creating-packages/#register

Hope to see the update soon. :)

**Comment by JustMaier** [comment]
Hey @PierrickGT,

I actually just had to bump the version. It was still pulling the old v0.1.2 code on `bower install`. After bumping the version to v0.1.3 it works as expected. Thanks again for the heads up.
