### ISSUE TITLE
Single Value

### ISSUE THREAD

**Issue by daviddfa** [JustMaier/angular-ranger#5]
Is there a way to make only single value ranger?

**Comment by JustMaier** [comment]
Hey @jdfa14, there isn't a way right now, but I'll be adding this functionality soon.

**Comment by doug62** [comment]
Another vote for single value - this is 1% away from perfect (and useable).... But thanks for the effort

**Comment by ehsaanwelcome** [comment]
+1

**Comment by JustMaier** [comment]
Sorry it took so long to get this implemented. You can now do single value sliders simple by using just `value` instead of `min-value/max-value`
