### ISSUE TITLE
How to determine change event

### ISSUE THREAD

**Issue by ziofat** [JustMaier/angular-ranger#9]
I want to fire a change event when the slider values have been changed. However, without ngModel, it seems I can not have a ngChange in the directive.
I don't want to use $watch in my situation because there are several sliders created by ngRepeat, and I wants to know which one fire the change event.

Is there clean way to do that?

**Comment by JustMaier** [comment]
Is there a reason you can't use ngModel? Two-way binding in angular revolves around ngModel,

**Comment by ziofat** [comment]
Yes, I tried. However when using ngModel, changing on ngModel programmly will not change the slider value.
